import Header from "@/src/component/header/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Provider from "./Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <section className={`w-full h-full flex justify-center`}>
            <div className={`w-full h-full max-w-5xl`}>
              <div className={"border-b-2"}>
                <Header />
              </div>
              <div>{children}</div>
            </div>
          </section>
        </Provider>
      </body>
    </html>
  );
}
